Automatically jumps to the next photo when deleting while previewing.
filebrowser/filebrowser pull request #1143
Opened 2020-11-11 02:37 UTC by chief8192

**Description**
Deletions made while previewing now immediately load the preview of the next file in the list. When the last file is deleted, previewing ends and returns to the file list, as before.

Closes #1091

2020-11-11 09:18 UTC, o1egl commented
@ramiresviana could you please review it?

2020-11-11 13:40 UTC, ramiresviana requested changes
There is an issue when pressing enter on delete dialog, the `next()` is being triggered. This should be solved by:

- Moving `this.closeHovers()` to after `this.$emit` on https://github.com/filebrowser/filebrowser/blob/dcbc3286e20aca45a605a3cc8ba741f1fa251424/frontend/src/components/prompts/Delete.vue#L35
- Changing the `keyup` to `keydown` on https://github.com/filebrowser/filebrowser/blob/dcbc3286e20aca45a605a3cc8ba741f1fa251424/frontend/src/components/files/Preview.vue#L136-L142
- Removing `event.preventDefault()` on https://github.com/filebrowser/filebrowser/blob/dcbc3286e20aca45a605a3cc8ba741f1fa251424/frontend/src/components/files/Preview.vue#L158

2020-11-11 13:40 UTC, ramiresviana commented on frontend/src/components/prompts/Delete.vue
> +          this.$root.$emit('preview_deleted', this.$route.path)
Event names should be in kebab-case.

2020-11-11 13:40 UTC, ramiresviana commented on frontend/src/components/files/Preview.vue
> +    this.$root.$on('preview_deleted', this.deleted)
To listen events of the component you can use the `v-on:preview-deleted` tag or its shorthand `@preview-deleted`.

2020-11-11 13:40 UTC, ramiresviana commented on frontend/src/components/prompts/Delete.vue
> +          this.$root.$emit('preview_deleted', this.$route.path)
`$root` should be avoided and used only on edge cases, use `this.$emit('preview-deleted')` instead.

2020-11-11 13:40 UTC, ramiresviana commented on frontend/src/components/files/Preview.vue
> +        this.back()
`back()` closes the previewer, use `prev()` instead.

2020-11-11 13:40 UTC, ramiresviana commented on frontend/src/components/files/Preview.vue
> +        this.back()
When `!hasPrevious && !hasNext == true` the previewer should be closed.

2020-11-12 02:22 UTC, chief8192 commented
The problem I'm running into is that after omitting `$root` from `this.$root.$emit(...)` and `this.$root.$on(...)`, event transmission stops working. Seems like it could be because `Delete` and `Preview` are sibling components?

2020-11-12 11:54 UTC, ramiresviana commented
Just omitting `$root` from `this.$root.$on(...)` is not going to work, you need to use `v-on` directive on the components you want to listen: https://vuejs.org/v2/guide/events.html

2020-11-13 01:38 UTC, chief8192 commented
Yeah, so I've tried using `v-on`, in a number of different places. I can verify that the `this.$emit('preview-deleted')` call is working, because the event shows up in the devtools console when I click "DELETE".

The problem seems to be that `prompts/Delete.vue` is not a child component of `files/Preview.vue`. If I'm understanding [this article](https://www.telerik.com/blogs/how-to-emit-data-in-vue-beyond-the-vuejs-documentation) correctly, the `v-on` would have to be added to the `<delete>` tag that gets generated in `prompts/Prompts.vue`. It doesn't look like that could be done without a decent amount of refactoring, and even that wouldn't gain us the ability to interact with `Preview.vue`.

2020-11-13 12:54 UTC, ramiresviana commented
Every element that is on template body of the component is considered a child, so `<delete-button>` is child of the preview. A working example is the `<preview-size-button>`, it has `@change-size` event and is being used on the preview.

2020-11-17 11:36 UTC, chief8192 commented
I agree, what you're saying is true. The difference here is that while the Delete **button** is a child of the Preview component, the Delete **prompt** is not. And it's the Delete **prompt** which is ultimately responsible for making the API call to delete the file, and then calling `$emit()`.

So given the limitation here that an event emitted by a child component has to be handled by the parent component (either via `v-on` or `@event-name`), I'm not clear how this could be easily made to work, given that the parent component of the Delete prompt is `Prompts.vue`, not `Preview.vue`:

![filebrowser_components](https://user-images.githubusercontent.com/1092786/99385572-29bb8b80-289f-11eb-9169-e8a8a711afaa.png)

2020-11-17 12:21 UTC, ramiresviana commented
I see now, since VueJS does not provide an proper solution for that case, i think we can use the `$root` instance.

2020-11-18 01:16 UTC, chief8192 commented
Ok, committed a new round of changes

2020-11-18 12:43 UTC, ramiresviana requested changes
Navigation stops working when renaming file on preview, can you take a look on that? Similarly to the `prompts/Delete` you will need to create an event for `prompts/Rename`.

2020-11-18 12:43 UTC, ramiresviana commented on frontend/src/components/files/Preview.vue
>    beforeDestroy () {
Use `this.$root.$off('preview-deleted', this.deleted)` to stop listening the event.

2020-11-18 12:43 UTC, ramiresviana commented on frontend/src/components/files/Preview.vue
> +      this.listing = this.listing.filter(item => item.name !== deletedName)
```suggestion
      this.listing = this.listing.filter(item => item.name !== this.name)
```

2020-11-18 12:43 UTC, ramiresviana commented on frontend/src/components/files/Preview.vue
> +      } else if (!this.hasPrevious && !this.hasNext == true) {
```suggestion
      } else if (!this.hasPrevious && !this.hasNext) {
```

2020-11-22 13:22 UTC, chief8192 commented
I did a clean build from master, and the rename issue is present there as well, so it looks to be an unrelated issue out of scope for this PR.

2020-11-23 12:50 UTC, ramiresviana approved these changes
Looking good, thank you for contributing to this project.

2020-11-23 18:08 UTC, merged

2020-11-24 00:53 UTC, chief8192 commented
Cheers, happy to help!