feat: implemented hideDotfiles feature in the backend
filebrowser/filebrowser pull request #1148
Opened 2020-11-14 20:26 UTC by NieTiger

This PR addresses https://github.com/filebrowser/filebrowser/issues/1084.

Per @o1egl, I've rewritten my previous PR (https://github.com/filebrowser/filebrowser/pull/1085) to move the filtering logic to the backend. 

By default the `hideDotfiles` options is turned off, and it can be turned on in profile settings.

2020-11-17 12:20 UTC, o1egl requested changes

2020-11-17 12:20 UTC, o1egl commented on rules/rules.go
> +}
Let's use path prefix instead of regexp

2020-11-18 04:47 UTC, NieTiger commented on rules/rules.go
> +}
This needs to check if the first character of the base name is a dot. Does not work with `strings.HasPrefix`. Would still need a separate function that uses `filepath.Base`. Is that cool?

2020-11-18 09:22 UTC, o1egl commented on rules/rules.go
> +}
`\/\..*$` and `strings.HasPrefix("/.")` are equal. So I don't understand why it shouldn't work. Better would be to get the base name and then check if it starts from `.`

2020-11-18 09:28 UTC, NieTiger commented
The path provided to the function are relative paths with directory prefixes, so `strings.HasPrefix("/a/b/c/.docker.json", "/.”)` does not work and we’d need the base name. That’s just an extra import and sort of out of line with the rest of the rules because they’re all Regex, but if you wanna do let this way, I don’t mind.
On 18 Nov 2020, 5:22 PM +0800, Oleg Lobanov <notifications@github.com>, wrote:
> @o1egl commented on this pull request.
> In rules/rules.go:
> > +var MatchHidden = Rule{
> +       Regex:  true,
> +       Regexp: &Regexp{Raw: `\/\..*$`},
> +}
> \/\..*$ and strings.HasPrefix("/.") are equal. So I don't understand why it shouldn't work. Better would be to get the base name and then check if it starts from .
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-11-18 09:33 UTC, o1egl commented
Prefix based comparison is much faster than the regexp.

2020-11-18 10:24 UTC, NieTiger commented on rules/rules.go
> +}
I've updated the PR.

2020-11-18 13:18 UTC, o1egl reviewed
nit

2020-11-18 13:18 UTC, o1egl commented on rules/rules.go
> +	return filepath.Base(path)[0] == '.'
It will cause panic on empty string. 
```suggestion
	return strings.HasPrefix(filepath.Base(path, "."))
```

2020-11-18 13:18 UTC, o1egl commented on rules/rules_test.go
> +	for path, truth := range cases {
```suggestion
	for path, want := range cases {
```

2020-11-18 15:39 UTC, o1egl commented on rules/rules_test.go
> +			t.Errorf("MatchHidden(%s)=%v; want %v", path, got, truth)
```suggestion
		if got != want {
			t.Errorf("MatchHidden(%s)=%v; want %v", path, got, want)
```

2020-11-19 06:13 UTC, NieTiger commented
Any more changes needed?

2020-11-20 10:49 UTC, o1egl approved these changes

2020-11-20 10:51 UTC, merged

2021-01-20 04:06 UTC, smithzss commented
@NieTiger @o1egl Is this a configurable option when launching in a docker container?  I looked in the source and I didn't see anything that would suggest it, but I wanted to ask to confirm.  Didn't see it in the documentation as well.  I am looking for dotfiles to be hidden by default.  Appreciate the help!  Thanks.

2021-01-20 08:48 UTC, o1egl commented
@smithzss this param is only available in the UI.

2021-04-12 20:39 UTC, pdesgarets commented
@o1egl would you consider a PR implementing a flag for this param in the Cmd ?