add sharing management
filebrowser/filebrowser pull request #1178
Opened 2020-12-07 07:11 UTC by WeidiDeng

**Description**
Added sharing management. Normal user can only see own shares, admin sees all.
Fixes [issuse](https://github.com/filebrowser/filebrowser/issues/1000)

:rotating_light: Before submitting your PR, please read [community](https://github.com/filebrowser/community), and indicate which issues (in any of the repos) are either fixed or closed by this PR. See [GitHub Help: Closing issues using keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

- [ ] DO make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [ ] DO make sure you are making a pull request against the **master branch** (left side). Also you should start *your branch* off *our master*.
- [ ] DO make sure that File Browser can be successfully built. See [builds](https://github.com/filebrowser/community/blob/master/builds.md) and [development](https://github.com/filebrowser/community/blob/master/development.md).
- [ ] DO make sure that related issues are opened in other repositories. I.e., the frontend, caddy plugins or the web page need to be updated accordingly.
- [ ] AVOID breaking the continuous integration build.

**Further comments**
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did, what alternatives you considered, etc.

:heart: Thank you!

2020-12-10 12:50 UTC, ramiresviana requested changes

2020-12-10 12:50 UTC, ramiresviana commented on frontend/src/views/settings/Shares.vue
> +    this.clip.on('success', () => {
This event listener should be removed when the component is destroyed, similar to the share prompt.

2020-12-12 13:03 UTC, o1egl requested changes

2020-12-12 13:03 UTC, o1egl commented on http/http.go
> +	api.Path("/shares").Handler(monkey(shareListHandler, "")).Methods("GET")
```suggestion
	api.Path("/shares").Handler(monkey(shareListHandler, "/api/shares")).Methods("GET")
```

2020-12-12 13:03 UTC, o1egl commented on share/storage.go
> +	List(id uint) ([]*Link, error)
Let's rename it to `FindByUserID`

2020-12-12 13:03 UTC, o1egl commented on http/share.go
> +	s, err := d.store.Share.List(id)
Instead of defining magic constants let's add `All()` method to the store for admin users

2020-12-24 18:00 UTC, o1egl approved these changes

2020-12-24 18:02 UTC, merged