download shared subdirectory
filebrowser/filebrowser pull request #1184
Opened 2020-12-11 10:56 UTC by WeidiDeng

**Description**
Currently shared folder can't be navigated like a real folder, only direct subdirectory and files can be viewed, but not downloadable separately.

This pr fixes [issue](https://github.com/filebrowser/filebrowser/issues/1162#issuecomment-734709064). Folders can be navigated and select files can be downloaded.

:rotating_light: Before submitting your PR, please read [community](https://github.com/filebrowser/community), and indicate which issues (in any of the repos) are either fixed or closed by this PR. See [GitHub Help: Closing issues using keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

- [ ] DO make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [ ] DO make sure you are making a pull request against the **master branch** (left side). Also you should start *your branch* off *our master*.
- [ ] DO make sure that File Browser can be successfully built. See [builds](https://github.com/filebrowser/community/blob/master/builds.md) and [development](https://github.com/filebrowser/community/blob/master/development.md).
- [ ] DO make sure that related issues are opened in other repositories. I.e., the frontend, caddy plugins or the web page need to be updated accordingly.
- [ ] AVOID breaking the continuous integration build.

**Further comments**
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did, what alternatives you considered, etc.

:heart: Thank you!

2020-12-12 13:25 UTC, o1egl reviewed
I found a bug that when you double click on a file which has `#` in its name the blank page is displayed.

2020-12-14 12:57 UTC, ramiresviana commented
- The information panel has some inconsistency when selecting a list item, only part of its information is being updated, that can cause user confusion about which item will actually be downloaded.
- The "Select multiple" feels out of place, lets move it to the header bar.
- The current routing allows to insert an arbitrary string to the path, like /share/I2cD5Vvw/\*anything\*. Also i think we should omit the root directory from the url.

2020-12-15 00:31 UTC, WeidiDeng commented
> * The information panel has some inconsistency when selecting a list item, only part of its information is being updated, that can cause user confusion about which item will actually be downloaded.

Which parts should be updated?



> * The "Select multiple" feels out of place, lets move it to the header bar.

I plan to make it more like the multiple style in the file listing page when I have time



> * The current routing allows to insert an arbitrary string to the path, like /share/I2cD5Vvw/*anything*. Also i think we should omit the root directory from the url.

Abitratry path can be detected in the backend, I don't think that's an issue, normal user won't bother changing url by hand.

The root directory potion is automatically filled. It's actually essential. According to [this comment](https://github.com/filebrowser/filebrowser/blob/bc4a6462ced43a1f754b8ad4aae2d770a1750051/http/public.go#L43). Say we share a directory a, there are dir a, b, c below it. When a request for /api/public/dl/hash/a came, which a is it, the root a or a below it, removing the trailing filename would fix it, but that leads to ugly download url a/a, 1.mp4/mp4. I did it in the previous commit. Also this means err check can't distinguish between two file with same name.

If root directory is only not shown in the address bar, there is quite a lot to do when someone use the subdirectory url to access the subdirectory, thanks to [this comment](https://github.com/filebrowser/filebrowser/blob/bc4a6462ced43a1f754b8ad4aae2d770a1750051/http/public.go#L43). Not appending filename when downloading can fix them pretty easily.

I think if root directory name is a thing, it can be checked. And normally user won't bother tickering with urls.

2020-12-15 12:18 UTC, ramiresviana commented
I see 2 ways to resolve the info panel issue:

1. Update the icon, displayName, lastModified, size, downloadButton and qrcode when selecting an item. Also the panel should have a different state for multiple selections, showing only number of selected items and total size.
2. The panel will show only the information of the current directory/file. Downloading selected items is done by clicking on a button on the header bar, similar to the normal Filebrowser listing.

2020-12-21 11:48 UTC, ramiresviana requested changes

2020-12-21 11:48 UTC, ramiresviana commented on frontend/src/components/Header.vue
> +      <template v-if="isSharing">
Instead of creating a whole new dropdown, lets use the `v-show` directive on the wanted elements.

2020-12-21 11:48 UTC, ramiresviana commented on frontend/src/components/Header.vue
> +          <button @click="toggleSharedMultipleSelection" :aria-label="$t('buttons.selectMultiple')" :title="$t('buttons.selectMultiple')" class="action" >
Can we reuse the existing selection toggle and download buttons?

2020-12-21 11:48 UTC, ramiresviana commented on frontend/src/store/index.js
> +    req: {},
I think we can reuse the current existing state properties. Also you can make the hash work as a getter using only the req state.

2020-12-28 16:35 UTC, merged