fix search by type
filebrowser/filebrowser pull request #1228
Opened 2021-01-05 09:41 UTC by WeidiDeng

**Description**
Currently, when searching by type, filebrowser shows up nothing. Because there is only a return nil on that execution path.

:rotating_light: Before submitting your PR, please read [community](https://github.com/filebrowser/community), and indicate which issues (in any of the repos) are either fixed or closed by this PR. See [GitHub Help: Closing issues using keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

- [ ] DO make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [ ] DO make sure you are making a pull request against the **master branch** (left side). Also you should start *your branch* off *our master*.
- [ ] DO make sure that File Browser can be successfully built. See [builds](https://github.com/filebrowser/community/blob/master/builds.md) and [development](https://github.com/filebrowser/community/blob/master/development.md).
- [ ] DO make sure that related issues are opened in other repositories. I.e., the frontend, caddy plugins or the web page need to be updated accordingly.
- [ ] AVOID breaking the continuous integration build.

**Further comments**
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did, what alternatives you considered, etc.

:heart: Thank you!

2021-01-11 23:27 UTC, o1egl commented
Can you please describe how to reproduce it? When i make a search with provided type I get expected results

2021-01-11 23:52 UTC, WeidiDeng commented
In the search bar click one of the four predefined types and enter, no result was given. Directly enter extension did work.

2021-01-12 10:06 UTC, o1egl commented
Oh, you mean search with empty query?

2021-01-12 10:11 UTC, o1egl requested changes

2021-01-12 10:11 UTC, o1egl commented on search/search.go
> +					return found(originalPath, f)
This is not correct. If user entered a search query the result will not be filtered.

2021-01-12 10:11 UTC, o1egl commented on search/search.go
> +		originalPath = strings.TrimPrefix(originalPath, "/")
Why is this change being introduced?

2021-01-12 17:08 UTC, merged