Fix environmental variable expansion
filebrowser/filebrowser pull request #1241
Opened 2021-01-12 14:44 UTC by WeidiDeng

**Description**
Fix [1211](https://github.com/filebrowser/filebrowser/issues/1211).

:rotating_light: Before submitting your PR, please read [community](https://github.com/filebrowser/community), and indicate which issues (in any of the repos) are either fixed or closed by this PR. See [GitHub Help: Closing issues using keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

- [ ] DO make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [ ] DO make sure you are making a pull request against the **master branch** (left side). Also you should start *your branch* off *our master*.
- [ ] DO make sure that File Browser can be successfully built. See [builds](https://github.com/filebrowser/community/blob/master/builds.md) and [development](https://github.com/filebrowser/community/blob/master/development.md).
- [ ] DO make sure that related issues are opened in other repositories. I.e., the frontend, caddy plugins or the web page need to be updated accordingly.
- [ ] AVOID breaking the continuous integration build.

**Further comments**
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did, what alternatives you considered, etc.

:heart: Thank you!

2021-01-13 09:13 UTC, o1egl requested changes
Please remove search related commits from this pr.

2021-01-13 09:13 UTC, o1egl commented on runner/runner.go
> +			return os.Getenv(key)
I think using global env is not safe. Let's use an empty string as a default value

2021-01-19 15:57 UTC, o1egl commented
@WeidiDeng please remove the expansion of any env variable by default.

2021-01-19 16:02 UTC, merged

2021-01-23 01:49 UTC, WeidiDeng commented
I found out that there is a global setting called ```Execute on shell``` that is supposed to do the envars expansion. Guess that's overlooked.