Search box border fixed
filebrowser/filebrowser pull request #1613
Opened 2021-10-13 00:34 UTC by niubility000

current:
![1](https://user-images.githubusercontent.com/76441520/137047108-7667c454-c372-4901-81b4-3cac5ef92be5.png)

fixed:
![2](https://user-images.githubusercontent.com/76441520/137047128-f3ed3269-818d-43da-8e85-3d3e832262af.png)

2021-10-13 11:44 UTC, ramiresviana requested changes

2021-10-13 11:44 UTC, ramiresviana commented on frontend/src/css/header.css
> +  height: 3em;
```suggestion
  height: 100%;
```

2021-10-14 03:33 UTC, niubility000 commented on frontend/src/css/header.css
> +  height: 3em;
Done.

2021-10-14 11:35 UTC, ramiresviana approved these changes
This PR fixes the issue where search box is misaligned when the browser preferred font size is other than 16px.

2021-10-19 16:34 UTC, merged