fixed sidebar function again
filebrowser/filebrowser pull request #1618
Opened 2021-10-14 06:41 UTC by niubility000

fixed #1575
fixed #1576

Ramiresviana, this time, I change the route-link to button. and also use "replace" to solve the the problem of "back" button function.

2021-10-15 00:27 UTC, niubility000 commented
I change "replace" to "push". Replace only save one "back" button click and may confuse the user.

2021-10-15 12:09 UTC, ramiresviana requested changes

2021-10-15 12:09 UTC, ramiresviana commented on frontend/src/components/Sidebar.vue
> +         :title="$t('sidebar.myFiles')"
```suggestion
        class="action"
        @click="toRoot"
        :aria-label="$t('sidebar.myFiles')"
        :title="$t('sidebar.myFiles')"
```

2021-10-15 12:09 UTC, ramiresviana commented on frontend/src/components/Sidebar.vue
> +           :title="$t('sidebar.settings')"
```suggestion
          class="action"
          @click="toSettings"
          :aria-label="$t('sidebar.settings')"
          :title="$t('sidebar.settings')"
```

2021-10-15 12:09 UTC, ramiresviana commented on frontend/src/components/Sidebar.vue
> +    },
```suggestion
    toRoot() {
      this.$router.push({ path: "/files/" }, () => {});
      this.$store.commit("closeHovers");
    },
    toSettings() {
      this.$router.push({ path: "/settings" }, () => {});
      this.$store.commit("closeHovers");
    },
```

2021-10-18 14:08 UTC, ramiresviana approved these changes

2021-10-19 16:37 UTC, merged