Fix hook Method login rules were erased and rule permissions were add…
filebrowser/filebrowser pull request #2509
Opened 2023-06-19 08:03 UTC by zhizhi10

**Further comments**
1.Fix hook Method login rules were erased and rule permissions were added in the validation script.
2.You can add the following rule to the validation script, and the hook won't erase your existing rules when you don't use it.  
Each rule is separated by a semicolon.Hook method from https://github.com/filebrowser/filebrowser/pull/1554
`echo 'user.perm.rule     = {"regex": false,"allow": true,"path": "/data","regexp":{"raw": ""}};{"regex": true,"allow": false,"path": "","regexp":{"raw": "sh"}}'
`

2023-07-22 20:59 UTC, o1egl requested changes

2023-07-22 20:59 UTC, o1egl commented on auth/hook.go
> +	"user.perm.rule",
```suggestion
	"user.perm.rules",
```

2023-07-22 20:59 UTC, o1egl commented on auth/hook.go
> +		Rules:        a.Fields.GetRules("user.perm.rule", d.Rules),
```suggestion
		Rules:        a.Fields.GetRules("user.perm.rules", d.Rules),
```

2023-07-22 20:59 UTC, o1egl commented on auth/hook.go
> +	for _, ruleString := range strings.Split(val, ";") {
If we expect a rule to be encoded as a json, why not to simply return a json array instead of semicolon separated  objects?

2023-07-22 20:59 UTC, o1egl commented on auth/hook.go
> +			return dv
Let's write this error to the log for better auditability

2023-08-12 13:47 UTC, zhizhi10 reviewed
I have modified the code according to your suggestion

2023-08-26 22:35 UTC, o1egl commented on auth/hook.go
> +	var Rules []rules.Rule
In go by convention all the variables should start from the lower case. You can rename it to `userRules` or something like that

2023-08-26 22:36 UTC, o1egl requested changes
Please fix go lint errors

2023-09-01 13:47 UTC, zhizhi10 commented
![图片](https://github.com/filebrowser/filebrowser/assets/97386874/b83bee93-b5d7-468c-bab0-b413f33f49d0)
Rename `Rules` to `userRules`
Fixed go lint errors

2023-10-24 01:44 UTC, closed without merging